@---------------------------------------------------------------------------------
@ 3DS processor selection
@---------------------------------------------------------------------------------
    .cpu mpcore
@---------------------------------------------------------------------------------

@---------------------------------------------------------------------------------
    .section ".crt0"
    .global _start, __service_ptr
@---------------------------------------------------------------------------------
    .align 4
    .arm
@---------------------------------------------------------------------------------
_start:
@---------------------------------------------------------------------------------
    b startup
__service_ptr:
    .word 0 @ Pointer to service handle override list -- necessary to use some of ctrulib functions
startup:
    @ Save return address
    mov     r4, lr

    @ Clear the BSS section
    ldr     r0, =__bss_start__
    ldr     r1, =__bss_end__
    sub     r1, r1, r0
    bl      ClearMem

    @ Jump to plugin init code
    ldr     R0, [SP]
    sub     R1, SP, #0x100 @ 0x07000000
    bl      __entrypoint

    @ Jump back to plugin loader hook
    mov     pc, r4

@---------------------------------------------------------------------------------
@ Clear memory to 0x00 if length != 0
@  r0 = Start Address
@  r1 = Length
@---------------------------------------------------------------------------------
ClearMem:
@---------------------------------------------------------------------------------
    mov     r2, #3     @ Round down to nearest word boundary
    add     r1, r1, r2 @ Shouldnt be needed
    bics    r1, r1, r2 @ Clear 2 LSB (and set Z)
    bxeq    lr         @ Quit if copy size is 0

    mov     r2, #0
ClrLoop:
    stmia   r0!, {r2}
    subs    r1, r1, #4
    bne     ClrLoop

    bx      lr



/* This code was generated by Gemini PRO.

    .arm
    .text

    bl srvInit
    bl plgLdrInit

    @ -------------------------------------------------------
    @ 1. イベント作成
    @ -------------------------------------------------------
    ldr r0, =g_continueGameEvent
    mov r1, #1
    bl _svcCreateEvent

    @ -------------------------------------------------------
    @ 2. メインスレッド作成
    @ -------------------------------------------------------
    @ スタック引数の準備 (r0-r3に干渉しないよう、先にスタックへ直値で配置)
    mov r12, #-1
    str r12, [sp, #-4]!
    mov r12, #30
    str r12, [sp, #-4]!
    
    ldr r0, =g_mainThreadHandle
    ldr r1, =mainThread
    mov r2, #0
    ldr r3, =mainstack_top
    bl _svcCreateThread
    add sp, sp, #8

    @ -------------------------------------------------------
    @ 3. モニタースレッド作成
    @ -------------------------------------------------------
    mov r12, #-1
    str r12, [sp, #-4]!
    mov r12, #31
    str r12, [sp, #-4]!
    
    ldr r0, =g_monitor_ThreadHandle
    ldr r1, =MonitorDeamon_Thread
    mov r2, #0
    ldr r3, =monitorstack_top
    bl _svcCreateThread
    add sp, sp, #8

    @ -------------------------------------------------------
    @ 4. 同期待ち & クローズ処理
    @ -------------------------------------------------------
    ldr r0, =g_continueGameEvent
    mov r1, #0xFFFFFFFF
    mov r2, #0xFFFFFFFF
    bl _svcWaitSynchronization

    ldr r0, =g_continueGameEvent
    bl _svcCloseHandle

    ldr r0, =g_monitor_ThreadHandle
    bl _svcCloseHandle

    ldr r0, =g_mainThreadHandle
    bl _svcCloseHandle

    @ -------------------------------------------------------
    @ 5. 終了処理
    @ -------------------------------------------------------
    bl srvExit
    bl plgLdrExit


    @ =======================================================
    @ SERVICE LABELS (SVC WRAPPERS)
    @ =======================================================
_svcCreateThread:
    svc 0x08
    bx lr

_svcCreateEvent:
    svc 0x17
    bx lr

_svcWaitSynchronization:
    ldr r0, [r0]        @ ラベル側でポインタからハンドル値をデリファレンス
    svc 0x18
    bx lr

_svcCloseHandle:
    ldr r0, [r0]        @ ラベル側でポインタからハンドル値をデリファレンス
    svc 0x23
    bx lr
*/
