name: さんじーえっくすのさくせい

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y libcurl4-openssl-dev
          # dkp-pacman の実行は403エラーになるため削除。
          # 必要な 3ds-dev と 3ds-curl はコンテナに内蔵されています。

      - name: Build
        run: |
          make

      - name: Prepare for deployment
        run: |
          mkdir -p publish
          if [ -f ./mk7_session_players_viewer-debug.3gx ]; then
            cp ./mk7_session_players_viewer-debug.3gx publish/mk7_session_players_viewer-debug.3gx
          elif [ -f ./mk7_session_players_viewer-release.3gx ]; then
            cp ./mk7_session_players_viewer-release.3gx publish/mk7_session_players_viewer-debug.3gx
          else
            TARGET_FILE=$(find . -maxdepth 1 -type f -name '*.3gx' | head -n 1)
            if [ -n "$TARGET_FILE" ]; then
              cp "$TARGET_FILE" publish/mk7_session_players_viewer-debug.3gx
            else
              echo "Error: .3gx file not found."
              exit 1
            fi
          fi

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
