name: さんじーえっくすのさくせい

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkitarm

    steps:
    - uses: actions/checkout@v4

    - name: つくる
      run: make release

    - name: あげる
      uses: actions/upload-artifact@v4
      with:
        name: out
        path: ./
